### ISSUE TITLE
Support SD cards

### ISSUE THREAD

**Issue by jhalterman** [eladnava/pixelmate#1]
Would be nice if pixelmate supported SIM cards in addition to data on the actual device, similar to what Android File Transfer supports.

**Comment by jhalterman** [comment]
Arg - my mistake - I meant SD cards :) I don't have a screenshot handy, but at the top of Android File Transfer there's a tab that lets you select between the internal storage and the SD card.

**Comment by eladnava** [comment]
Hi @jhalterman,
That is a great suggestion!

Do you happen to know the paths for each storage partition? Pixelmate by default sets the root to `/sdcard` which appears to be the internal storage?

**Comment by jhalterman** [comment]
Yea - I get internal storage using pixelmate. I'm not sure how to access an SD card.

**Comment by jhalterman** [comment]
I'm using a Galaxy S9. A quick check with adb: `/sdcard` symilinks to `/storage/self/primary`. My actual sd card is `/storage/9C33-6BBD`. I'm not sure if there's an API to properly enumerate the contents of storage.

**Comment by jhalterman** [comment]
Basic approach: list the contents of `/storage` and support navigating to anything that is a directory and readable.

**Comment by eladnava** [comment]
Hi @jhalterman,
That might just work.

Is the internal memory also at `/storage/self/primary` for you?

**Comment by eladnava** [comment]
@jhalterman What if there was an option in Pixelmate's menu bar on OS X called **Navigate** that would allow you to enter a path to be navigated to? 

You could then enter `/storage` and Pixelmate will display the various media storage devices in the folder view.

I think this would be one way to do it as I think the `9C33-6BBD` may be too specific to the S9 or even your specific micro SD card.

**Comment by jhalterman** [comment]
Being able to navigate in storage would be better than nothing. I don't think `9C33-6BBD` is specific to S9 or my SD though. Lots of older [google hits](https://www.google.com/search?q=9C33-6BBD) for it.

**Comment by eladnava** [comment]
@jhalterman I just tried to insert a micro SD card on my Galaxy S9 and the storage path for it was `/storage/7000-8000`. I think it would be best if we not hard-code these names as there may be more variation.

**Comment by eladnava** [comment]
Added an option **All Storage Devices** in the OS X menu bar (or `Cmd + A`) which will navigate the remote file browser to `/storage`, where you can choose to browse the internal SD card or the external one.

Get version 1.0.1 here:
https://github.com/eladnava/pixelmate/releases/tag/1.0.1
