### ISSUE TITLE
Sign Pixelmat.app

### ISSUE THREAD

**Issue by timbroder** [eladnava/pixelmate#3]
![image](https://user-images.githubusercontent.com/121503/43721655-669fc216-9961-11e8-8d95-4b6043361c3a.png)

**Comment by eladnava** [comment]
@timbroder Great tip. I'm already paying for the Apple Developer Membership so this should be pretty straightforward. Will get to this in a few days probably.

**Comment by eladnava** [comment]
@timbroder Done:
https://github.com/eladnava/pixelmate/releases/tag/1.0.2
