### ISSUE TITLE
Angularjs 6: “'git' is not recognized as an internal or external command, operable program or batch file.”

### ISSUE THREAD

**Issue by faizy6641** [eladnava/pixelmate#4]
Hi,
Env Detail: Angular CLI: 6.1.3 Node: 8.11.3 npm version: 5.6.0
When i am trying to create an angular project by executing "ng new Project-name",i am getting " 'git' is not recognized as an internal or external command, operable program or batch file." instead of 'project name successfully created'

Response:

C:\Users\faizy\Desktop\AngularJs>ng new oshop
CREATE oshop/angular.json (3539 bytes)
CREATE oshop/package.json (1310 bytes)
CREATE oshop/README.md (1022 bytes)
CREATE oshop/tsconfig.json (408 bytes)
CREATE oshop/tslint.json (2805 bytes)
CREATE oshop/.editorconfig (245 bytes)
CREATE oshop/.gitignore (503 bytes)
CREATE oshop/src/favicon.ico (5430 bytes)
CREATE oshop/src/index.html (292 bytes)
CREATE oshop/src/main.ts (370 bytes)
CREATE oshop/src/polyfills.ts (3194 bytes)
CREATE oshop/src/test.ts (642 bytes)
CREATE oshop/src/styles.css (80 bytes)
CREATE oshop/src/browserslist (375 bytes)
CREATE oshop/src/karma.conf.js (964 bytes)
CREATE oshop/src/tsconfig.app.json (170 bytes)
CREATE oshop/src/tsconfig.spec.json (256 bytes)
CREATE oshop/src/tslint.json (314 bytes)
CREATE oshop/src/assets/.gitkeep (0 bytes)
CREATE oshop/src/environments/environment.prod.ts (51 bytes)
CREATE oshop/src/environments/environment.ts (642 bytes)
CREATE oshop/src/app/app.module.ts (314 bytes)
CREATE oshop/src/app/app.component.html (1141 bytes)
CREATE oshop/src/app/app.component.spec.ts (992 bytes)
CREATE oshop/src/app/app.component.ts (209 bytes)
CREATE oshop/src/app/app.component.css (0 bytes)
CREATE oshop/e2e/protractor.conf.js (752 bytes)
CREATE oshop/e2e/tsconfig.e2e.json (213 bytes)
CREATE oshop/e2e/src/app.e2e-spec.ts (301 bytes)
CREATE oshop/e2e/src/app.po.ts (208 bytes)
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump

> node-sass@4.9.3 install C:\Users\faizy\Desktop\AngularJs\oshop\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\faizy\AppData\Roaming\npm-cache\node-sass\4.9.3\win32-x64-57_binding.node

> node-sass@4.9.3 postinstall C:\Users\faizy\Desktop\AngularJs\oshop\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\faizy\Desktop\AngularJs\oshop\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1093 packages in 405.138s
'git' is not recognized as an internal or external command,
operable program or batch file.
![git](https://user-images.githubusercontent.com/30418618/43996377-4b1b1f18-9ddf-11e8-9cf4-2e853298e5ed.PNG)

**Comment by KlaussMC** [comment]
Am I correct in thinking you have the wrong repo?

this is pixelmate, not angular.

**Comment by eladnava** [comment]
Yes, wrong repo.

**Comment by faizy6641** [comment]
@eladnava what does it mean wrong repo?
by the way,my issue is resolve now

**Comment by KlaussMC** [comment]
You posted this to the wrong repository, this one is meant to fix a bug with the google pixel, and does not even mention angular, your problem is one mentioning angular.
