### ISSUE TITLE
I tried to package it myself, but the app is not working. 

### ISSUE THREAD

**Issue by mmm117** [eladnava/pixelmate#8]
Hi, I downloaded the source code, then I tried to package it myself, but the app is not working. 

This is the command I used to package it: 
electron-packager ./ "Pixelmate" --platform=mas --arch=x64 --icon=app --overwrite --electron-version=2.0.9 --app-bundle-id="com.abc.app" --app-version="1.0.1" --build-version="1"

The Main window shown up, but it was empty.  
I installed your app and I can see the files from my Samsung device, so connection is no problem. 

What is missing? Do I have to codesign it to make it work?

Thanks!

**Comment by eladnava** [comment]
Hi @mmm117,
Please use the following commands to package for `osx`:

```
git clone https://github.com/eladnava/pixelmate.git
cd pixelmate
npm install
npm run build
electron-packager . Pixelmate --electron-version=1.7.11 --platform=darwin --arch=x64 --icon=public/app.icns --version=1.0.0 --app-bundle-id=com.pixelmate --app-version=1.0.0 --build-version=1.0.0 --overwrite
zip -r -y -X dist/Pixelmate.zip Pixelmate-darwin-x64/Pixelmate.app
```

**Comment by KlaussMC** [comment]
No, to get the app working, the server needs to be active, in a separate CMD / terminal window, type `npm run server`, then run your app.

Sent from Mail for Windows 10

From: mmm117
Sent: Wednesday, 12 September 2018 10:55 PM
To: eladnava/pixelmate
Cc: Subscribed
Subject: [eladnava/pixelmate] I tried to package it myself, but the app is notworking. (#8)

Hi, I downloaded the source code, then I tried to package it myself, but the app is not working.
This is the command I used to package it:
electron-packager ./ "Pixelmate" --platform=mas --arch=x64 --icon=app --overwrite --electron-version=2.0.9 --app-bundle-id="com.abc.app" --app-version="1.0.1" --build-version="1"
The Main window shown up, but it was empty.
I installed your app and I can see the files from my Samsung device, so connection is no problem.
What is missing? Do I have to codesign it to make it work?
Thanks!

**Comment by eladnava** [comment]
@KlaussMC This is not necessary for packaged builds as `npm run build` generates a pre-made build of the HTML and JS files and no app server is necessary. The Electron app reads directly from the pre-built files.

**Comment by mmm117** [comment]
@eladnava @KlaussMC Hi, thanks for your help. I tried to follow the steps, but when I run "npm run build", it showed a lot of errors: 

----------------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild pixelmate@1.0.2
6 info build pixelmate@1.0.2
7 verbose unsafe-perm in lifecycle true
8 info pixelmate@1.0.2 Failed to exec build script
9 verbose stack Error: pixelmate@1.0.2 build: `react-scripts build`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid pixelmate@1.0.2
11 verbose cwd /Users/Shared/Shared Projects/Test/pixelmate
12 error Darwin 16.7.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
14 error node v4.4.4
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error pixelmate@1.0.2 build: `react-scripts build`
17 error Exit status 1
18 error Failed at the pixelmate@1.0.2 build script 'react-scripts build'.
18 error This is most likely a problem with the pixelmate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     react-scripts build
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs pixelmate
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls pixelmate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
 ----------------------------------------------------

Please help, thank you!!

**Comment by KlaussMC** [comment]
@eladnava right, yes. I was aware of that

**Comment by eladnava** [comment]
@mmm117 Please run this command separately and tell us the error returned:

```
react-scripts build
```

Also please make sure you have react-scripts installed globally:

```
npm install -g react-scripts@1.1.0
```

**Comment by KlaussMC** [comment]
Hi, would you please be able to say exactly what you did to get these results. Ie. Any commands you might have executed before / after the error?
Thanks.

Sent from Mail for Windows 10

**Comment by mmm117** [comment]
@eladnava , Hi, I did install "npm install -g react-scripts@1.1.0", but I needed to use "sudo" to install. 
When I run "react-scripts build", it showed this error: 

/usr/local/lib/node_modules/react-scripts/scripts/build.js:64
    ({ stats, previousFileSizes, warnings }) => {
     ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by eladnava** [comment]
@mmm117 What is your Node.js version?

`node -v`

**Comment by mmm117** [comment]
@KlaussMC Hi, as mentioned above, after I run "npm run build", it showed those error. 

git clone https://github.com/eladnava/pixelmate.git
cd pixelmate
npm install
npm run build

**Comment by mmm117** [comment]
v4.4.4

**Comment by mmm117** [comment]
@eladnava  v4.4.4

**Comment by KlaussMC** [comment]
@mmm117 that's probably why. upgrade to the latest version and see if that works

**Comment by eladnava** [comment]
Yes that would explain it. Please use latest LTS version 👍

**Comment by mmm117** [comment]
@eladnava @KlaussMC Should I install stable or latest?

sudo n stable
sudo n latest

**Comment by eladnava** [comment]
Both will work. 👍

**Comment by KlaussMC** [comment]
I would use the latest version.

**Comment by mmm117** [comment]
@eladnava @KlaussMC  Now when I try to run "npm install -g react-scripts@1.1.0" again, it still show some error: 

npm ERR! path /usr/local/lib/node_modules/react-scripts/node_modules/autoprefixer/node_modules/postcss/node_modules/chalk/node_modules/ansi-styles/node_modules/color-convert/node_modules/color-name
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/react-scripts/node_modules/autoprefixer/node_modules/postcss/node_modules/chalk/node_modules/ansi-styles/node_modules/color-convert/node_modules/color-name'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/react-scripts/node_modules/autoprefixer/node_modules/postcss/node_modules/chalk/node_modules/ansi-styles/node_modules/color-convert/node_modules/color-name'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/react-scripts/node_modules/autoprefixer/node_modules/postcss/node_modules/chalk/node_modules/ansi-styles/node_modules/color-convert/node_modules/color-name\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/react-scripts/node_modules/autoprefixer/node_modules/postcss/node_modules/chalk/node_modules/ansi-styles/node_modules/color-convert/node_modules/color-name' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Raymond/.npm/_logs/2018-09-15T13_25_11_914Z-debug.log

**Comment by KlaussMC** [comment]
`sudo npm install -g react-scripts@1.1.0` EACCESS is a permission error.

**Comment by mmm117** [comment]
MacBook-Pro-2:pixelmate Raymond$ react-scripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  77.94 KB  build/static/js/main.68726862.js
  588 B     build/static/css/main.92cfedfa.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  http://bit.ly/2vY88Kr

**Comment by KlaussMC** [comment]
Hey, There you go, that wasn't so hard, was it 😂??

**Comment by mmm117** [comment]
@eladnava Thanks, it finally works !

**Comment by KlaussMC** [comment]
Yay!!

**Comment by mmm117** [comment]
@KlaussMC Yes, I couldn't agree more...

**Comment by mmm117** [comment]
@eladnava @KlaussMC  I just found if I add "--asar" to package the app, it would fail to download file from my phone and show this error: 

Could not call remote function ''. Check that the function signature is correct. Underlying error: spawn ENOTDIR
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: spawn ENOTDIR
    at callFunction (/Users/Shared/Shared Projects/pixelmate/pixelmate-mas-x64/pixelmate.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Users/Shared/Shared Projects/pixelmate/pixelmate-mas-x64/pixelmate.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/Users/Shared/Shared Projects/pixelmate/pixelmate-mas-x64/pixelmate.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

**Comment by mmm117** [comment]
Also, the .app file is 877MB large.. why it is so large?

**Comment by eladnava** [comment]
Why are you using `--asar`??

**Comment by mmm117** [comment]
@eladnava I am new to Electron, just trying different options. So some Electron apps won't work with --asar option?  Thanks!

**Comment by eladnava** [comment]
@mmm117 Pixelmate won't. Not entirely sure why but it changes the file paths in the packaged project.

**Comment by mmm117** [comment]
@eladnava OK, i see, thanks!
