### ISSUE TITLE
Multi-selection for download

### ISSUE THREAD

**Issue by seljabali** [eladnava/pixelmate#9]
Firstly, thank you so much Elad for putting this application together! It really is my sole go to for file transferring. Secondly, I know you're already aware of this feature request, but I wanted to put it back on the radar to let you know people are using it. Let me know how I can donate to support the app.

Best!

**Comment by eladnava** [comment]
Hi @seljabali,
My pleasure! :) Happy to hear.

I'm a bit stressed for time but donations would indeed help prioritize this request. Feel free to PayPal eladnava [at] gmail.com, it is greatly appreciated 👍

**Comment by eladnava** [comment]
@seljabali Let me know if still interested in this.

**Comment by eladnava** [comment]
All done! 🎉 
[1.0.3](https://github.com/eladnava/pixelmate/releases/tag/1.0.3)

**Comment by seljabali** [comment]
I just saw this now! Thank you, it works great. Your Paypal should reflect a humble token of appreciation. 😃

**Comment by eladnava** [comment]
Cheers @seljabali!

It is greatly appreciated.
